<?php
global $pilot;
// add module layout to flexible content
$module = 'flexbox_slides';
$module_layout = array(
    'key' => create_key($module),
    'name' => 'flexbox_slides_block',
    'label' => 'Flexbox Slides Block',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => create_key($module,'columns'),
            'label' => 'Columns',
            'name' => 'flexbox_slides_columns',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Add Row',
            'sub_fields' => array(
                array(
                    'key' => create_key($module,'image'),
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => create_key($module,'column_title'),
                    'label' => 'Title',
                    'name' => 'column_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '255',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => create_key($module,'content'),
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'instructions' => '',
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                ),
                array(
                    'key' => create_key($module,'link'),
                    'label' => 'Link',
                    'name' => 'column_link',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '255',
                    'readonly' => 0,
                    'disabled' => 0,
                )),

        ),
    ),
    'min' => '',
    'max' => '',
);

?>