<?php
	global $pilot;
	// add module layout to flexible content 
	$module_layout = array (
					'key' => '56c8e4e1e3da2',
					'name' => 'multi_block',
					'label' => 'Half and Half Block',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56c8e4e1e3db0',
							'label' => 'Subtitle',
							'name' => 'multi_block_subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56c8e7c28c9ea',
							'label' => 'Content',
							'name' => 'multi_block_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_56c8e4e1e3da5',
							'label' => 'Background Image',
							'name' => 'multi_block_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56c8e4e1e3daa',
							'label' => 'Apply Filter to Image/Video',
							'name' => 'multi_block_modify',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_56c8e4e1e3dab',
							'label' => 'Opacity',
							'name' => 'multi_block_overlay_opacity',
							'type' => 'number',
							'instructions' => 'Set from 0 to 1 (for example 0.75)',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56c8e4e1e3daa',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 1,
							'step' => '.01',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56c8e4e1e3dac',
							'label' => 'Color',
							'name' => 'multi_block_overlay_color',
							'type' => 'color_picker',
							'instructions' => 'Set the color overlay for the image or video',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56c8e4e1e3daa',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_56c8e85201afa',
							'label' => 'Column Image',
							'name' => 'multi_block_column_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				);

?>