<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_57607da8934e1',
	'title' => 'Module Class Mapping',
	'fields' => array (
		array (
			'key' => 'field_57607db74bd2f',
			'label' => 'Modules',
			'name' => 'class_map_modules',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add a Module to Apply Class Maps to',
			'sub_fields' => array (
				array (
					'key' => 'field_57607f984bd31',
					'label' => 'Module Type',
					'name' => 'module_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'all' => 'All',
						'accordion' => 'accordion',
						'alternating' => 'alternating',
						'generic_content' => 'generic_content',
						'media' => 'media',
						'multi' => 'multi',
						'posts-slider' => 'posts-slider',
						'slider' => 'slider',
						'table' => 'table',
						'three-column-image-grid' => 'three-column-image-grid',
						'three_col' => 'three_col',
						'woo_table' => 'woo_table',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 1,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_57607f544bd30',
					'label' => 'Class Groups',
					'name' => 'class_groups',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add a Class Group (Like Font, Background, etc)',
					'sub_fields' => array (
						array (
							'key' => 'field_576082f65c9b8',
							'label' => 'Group Name',
							'name' => 'group_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 70,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_576084877a83c',
							'label' => 'Allow Multiple Choices',
							'name' => 'allow_multiple_choices',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 15,
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_5760830d5c9b9',
							'label' => 'Class Maps',
							'name' => 'class_maps',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 1000,
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add a Class Map',
							'sub_fields' => array (
								array (
									'key' => 'field_5760833e5c9ba',
									'label' => 'Class Selector (ie, "class-one")',
									'name' => 'selector',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5760838b5c9bb',
									'label' => 'Class Name',
									'name' => 'class_name',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'global-modules',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>