<?php
	global $pilot;
	// add module layout to flexible content 
	$module_layout = array (
		'key' => '5696bc8b7b7ca',
		'name' => 'accordion_block',
		'label' => 'Accordion Block',
		'display' => 'block',
		'sub_fields' => array (
			array (
				'key' => 'field_5696bca67b7cc',
				'label' => 'Content',
				'name' => 'accordion_block_content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
			),
			array (
				'key' => 'field_5696bcd27b7cd',
				'label' => 'Accordion Rows',
				'name' => 'accordion_block_rows',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
				'sub_fields' => array (
					array (
						'key' => 'field_5696be227b7ce',
						'label' => 'Lede',
						'name' => 'lede',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_5696be2a7b7cf',
						'label' => 'Hidden Content',
						'name' => 'hidden_content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
					),
				),
			),
		),
		'min' => '',
		'max' => '',
	);
?>