<?php
global $pilot;
// add module layout to flexible content
$module_layout = array(
    'key' => '567c402379f4e',
    'name' => 'media_block',
    'label' => 'Media Block',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_568c3e92d7c13',
            'label' => 'Type',
            'name' => 'media_block_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'image' => 'Image',
                'video_url' => 'Video',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'image : Image',
            'layout' => 'horizontal',
        ),
        array(
            'key' => 'field_568e6b7289c85',
            'label' => 'Width',
            'name' => 'media_block_width',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'full_width' => 'Full Width',
                'half_width' => 'Two Half Width Blocks',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
        ),
        array(
            'key' => 'field_567c403c0e631',
            'label' => 'Image',
            'name' => 'media_block_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568c3e92d7c13',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_568c45b9b87f9',
            'label' => 'Video MP4',
            'name' => 'media_video_file_mp4',
            'type' => 'file',
            'instructions' => 'Choose a MP4 video with a resolution of at least 1280x720',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568c3e92d7c13',
                        'operator' => '==',
                        'value' => 'video_url',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50%',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
        ),
        array(
            'key' => 'field_2b090963c8ab',
            'label' => 'Video Fallback Image',
            'name' => 'media_block_video_fallbackimage',
            'type' => 'image',
            'instructions' => 'A fallback image is required when showing video, in case the browser doesn\'t support video',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568c3e92d7c13',
                        'operator' => '==',
                        'value' => 'video_url',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50%',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_568c4ac9cde48',
            'label' => 'Apply Filter to Image',
            'name' => 'media_block_modify',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 30,
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
        ),
        array(
            'key' => 'field_568c4afdcde49',
            'label' => 'Opacity',
            'name' => 'media_block_overlay_opacity',
            'type' => 'number',
            'instructions' => 'Set from 0 to 1 (for example 0.75)',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568c4ac9cde48',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 35,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 0,
            'max' => 1,
            'step' => '.01',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_568c4c5cf3225',
            'label' => 'Color',
            'name' => 'media_block_overlay_color',
            'type' => 'color_picker',
            'instructions' => 'Set the color overlay for the image or video',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568c4ac9cde48',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 35,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_56943cf867a62',
            'label' => 'Logo or Title',
            'name' => 'media_block_logo_or_title',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'title' => 'Title',
                'logo' => 'Logo',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
        ),
        array(
            'key' => 'field_567c58eff6f30',
            'label' => 'Title',
            'name' => 'media_block_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_56943cf867a62',
                        'operator' => '==',
                        'value' => 'title',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_56943e1867a63',
            'label' => 'Logo',
            'name' => 'media_block_logo',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_56943cf867a62',
                        'operator' => '==',
                        'value' => 'logo',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_567c58fff6f31',
            'label' => 'Subtitle',
            'name' => 'media_block_subtitle',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_567c5919f6f32',
            'label' => 'Button Text',
            'name' => 'media_block_button_text',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
            ),
            'wrapper' => array(
                'width' => 33,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_569541f5e33a5',
            'label' => 'Button Link',
            'name' => 'media_block_button_href',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
            ),
            'wrapper' => array(
                'width' => 33,
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(),
            'taxonomy' => array(),
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_56af12ef29b5b',
            'label' => 'External Button Link',
            'name' => 'media_block_custom_button_href',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
            ),
            'wrapper' => array(
                'width' => 33,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_5762dr65873a',
            'label' => '2nd Type',
            'name' => 'media_block_type_second',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'image' => 'Image',
                'video_url' => 'Video',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'image : Image',
            'layout' => 'horizontal',
        ),
        array(
            'key' => 'field_56c9f0e7d7b1f',
            'label' => '2nd Image',
            'name' => 'media_block_image_second',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5762dr65873a',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_56c9f0f9d7b20',
            'label' => 'Video MP4',
            'name' => 'media_video_file_mp4_second',
            'type' => 'file',
            'instructions' => 'Choose a MP4 video with a resolution of at least 1280x720',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5762dr65873a',
                        'operator' => '==',
                        'value' => 'video_url',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
        ),
        array(
            'key' => 'field_28de2m7213j0356s',
            'label' => 'Video Fallback Image',
            'name' => 'media_block_video_fallbackimage_second',
            'type' => 'image',
            'instructions' => 'A fallback image is required when showing video, in case the browser doesn\'t support video',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5762dr65873a',
                        'operator' => '==',
                        'value' => 'video_url',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_56c9f21ad2fed',
            'label' => 'Apply Filter to 2nd Image',
            'name' => 'media_block_modify_second',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 30,
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
        ),
        array(
            'key' => 'field_56c9f238d2fee',
            'label' => 'Opacity on 2nd Image',
            'name' => 'media_block_overlay_opacity_second',
            'type' => 'number',
            'instructions' => 'Set from 0 to 1 (for example 0.75)',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_56c9f21ad2fed',
                        'operator' => '==',
                        'value' => '1',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 35,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 0,
            'max' => 1,
            'step' => '.01',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_56c9f253d2ff0',
            'label' => 'Color on 2nd Image',
            'name' => 'media_block_overlay_color_second',
            'type' => 'color_picker',
            'instructions' => 'Set the color overlay for the image or video',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_56c9f21ad2fed',
                        'operator' => '==',
                        'value' => '1',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 35,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
        ),
        array(
            'key' => 'field_56c9f26ed2ff2',
            'label' => 'Logo or Title on 2nd Block',
            'name' => 'media_block_logo_or_title_second',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'logo' => 'Logo',
                'title' => 'Title',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
        ),
        array(
            'key' => 'field_56c9f283d2ff3',
            'label' => '2nd Title',
            'name' => 'media_block_title_second',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_56c9f26ed2ff2',
                        'operator' => '==',
                        'value' => 'title',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_56c9f36e682e5',
            'label' => '2nd Logo',
            'name' => 'media_block_logo_second',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_56c9f26ed2ff2',
                        'operator' => '==',
                        'value' => 'logo',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_56c9f4b25e394',
            'label' => '2nd Subtitle',
            'name' => 'media_block_subtitle_second',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_56c9f4c95e395',
            'label' => '2nd Button Text',
            'name' => 'media_block_button_text_second',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 33,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_56c9f4e15e396',
            'label' => '2nd Button Link',
            'name' => 'media_block_button_href_second',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                    array(
                        'field' => 'field_568c3e92d7c13',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 33,
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(),
            'taxonomy' => array(),
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_56c9f51b5e398',
            'label' => '2nd External Button Link',
            'name' => 'media_block_custom_button_href_second',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_568c3e92d7c13',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_568e6b7289c85',
                        'operator' => '==',
                        'value' => 'half_width',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 33,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'min' => '',
    'max' => '',
);

?>